
export const LISTAGEM_EXTRATOS = '@cliente/LISTAGEM_EXTRATOS';
export const LISTAGEM_EXTRATOS_SUCCESS = '@cliente/LISTAGEM_EXTRATOS_SUCCESS';
export const LISTAGEM_EXTRATOS_FAILURE = '@cliente/LISTAGEM_EXTRATOS_FAILURE';

