export const CADASTRO_CLIENTE = '@cliente/CADASTRO_CLIENTE';
export const CADASTRO_CLIENTE_SUCCESS = '@cliente/CADASTRO_CLIENTE_SUCCESS';
export const CADASTRO_CLIENTE_FAILURE = '@cliente/CADASTRO_CLIENTE_FAILURE';
