export const CADASTRO_CLIENTE = '@cliente/CADASTRO_CLIENTE';
export const CADASTRO_CLIENTE_SUCCESS = '@cliente/CADASTRO_CLIENTE_SUCCESS';
export const CADASTRO_CLIENTE_FAILURE = '@cliente/CADASTRO_CLIENTE_FAILURE';

export const LISTAGEM_CLIENTES = '@cliente/LISTAGEM_CLIENTES';
export const LISTAGEM_CLIENTES_SUCCESS = '@cliente/LISTAGEM_CLIENTES_SUCCESS';
export const LISTAGEM_CLIENTES_FAILURE = '@cliente/LISTAGEM_CLIENTES_FAILURE';

export const ALTERAR_STATUS_CLIENTE = '@cliente/ALTERAR_STATUS_CLIENTE';
export const ALTERAR_STATUS_CLIENTE_SUCCESS =
  '@cliente/ALTERAR_STATUS_CLIENTE_SUCCESS';
export const ALTERAR_STATUS_CLIENTE_FAILURE =
  '@cliente/ALTERAR_STATUS_CLIENTE_FAILURE';

export const LISTAGEM_PRODUTOS_CLIENTES_SUCESSO = '@cliente/LISTAGEM_PRODUTOS_CLIENTES_SUCESSO';
export const LISTAGEM_PRODUTOS_CLIENTES = '@cliente/LISTAGEM_PRODUTOS_CLIENTES';
