export const CADASTRO_CLIENTE = '@cliente/CADASTRO_CLIENTE';
export const CADASTRO_CLIENTE_SUCCESS = '@cliente/CADASTRO_CLIENTE_SUCCESS';
export const CADASTRO_CLIENTE_FAILURE = '@cliente/CADASTRO_CLIENTE_FAILURE';

export const LISTAGEM_CLIENTES = '@cliente/LISTAGEM_CLIENTES';
export const LISTAGEM_CLIENTES_SUCCESS = '@cliente/LISTAGEM_CLIENTES_SUCCESS';
export const LISTAGEM_CLIENTES_FAILURE = '@cliente/LISTAGEM_CLIENTES_FAILURE';
