export const CADASTRO_PRODUTO = '@produto/CADASTRO_PRODUTO';
export const CADASTRO_PRODUTO_SUCCESS = '@produto/CADASTRO_PRODUTO_SUCCESS';
export const CADASTRO_PRODUTO_FAILURE = '@produto/CADASTRO_PRODUTO_FAILURE';

export const LISTAGEM_PRODUTOS = '@produto/LISTAGEM_PRODUTOS';
export const LISTAGEM_PRODUTOS_SUCCESS = '@produto/LISTAGEM_PRODUTOS_SUCCESS';
export const LISTAGEM_PRODUTOS_FAILURE = '@produto/LISTAGEM_PRODUTOS_FAILURE';
