export const AUTH_LOGIN = '@auth/LOGIN';
export const AUTH_LOGIN_SUCCESS = '@auth/LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = '@auth/LOGIN_FAILURE';

export const AUTH_RECUPERAR_SENHA_REQUEST = '@auth/RECUPERAR_SENHA_REQUEST';
export const AUTH_RECUPERAR_SENHA_SUCCESS = '@auth/RECUPERAR_SENHA_SUCCESS';
export const AUTH_RECUPERAR_SENHA_FAILURE = '@auth/RECUPERAR_SENHA_FAILURE';

export const AUTH_LOGOUT = '@auth/LOGOUT';
